---
services:
  registry:
    image: registry:latest
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ${REGISTRY_DATA_VOLUME}/data:/data
      - ${REGISTRY_DATA_VOLUME}/registry/auth:/auth
    networks:
      - npm_proxy

networks:
  npm_proxy:
    external: true